version: '3.5'

services:
  web:
    build: ./
    container_name: restaurant_web_container
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8100"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8100:8100"
    env_file:
      - ./.env
    depends_on:
      - db
  debug:
    build: ./
    container_name: restaurant_debug_container
    command: sleep infinity
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8101:8101"
    env_file:
      - ./.env
    stop_signal: SIGINT
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: restaurant_postgres_container
    image: "postgres:14"
    volumes:
      - ./.docker/data/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurant

volumes:
  postgres_data:
